apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-eureka-server
  labels:
    app: eureka-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            # Here we pull from the GLOBAL values file defined in the parent chart!
            # This is the "Aha!" moment for the interview.
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: {{ .Values.global.eurekaUrl | quote }}
            - name: MYSQL_HOST
              value: {{ .Values.global.mysql.host | quote }}
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.global.kafka.bootstrapServers | quote }}

