apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-banking-frontend
  labels:
    app: banking-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: banking-frontend
  template:
    metadata:
      labels:
        app: banking-frontend
    spec:
      containers:
        - name: banking-frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
