server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy API Gateway (Optional if Angular is compiled with environment pointed to Gateway IP directly)
    # Since they are all in docker compose, the browser calls localhost:8080.
    # NGINX just serves the static files.
}
