-- ============================================================
-- Phase 1 Test Data — Account Service
-- Run these after starting Account Service (port 8081)
-- Or use the cURL commands in README.md
-- ============================================================

USE account_db;

-- Insert 3 test accounts for end-to-end testing
-- NOTE: account_number is auto-generated by the service.
--       Use the API to create accounts and note the generated numbers.
--       These are sample inserts for direct DB testing only.

INSERT INTO accounts (account_number, customer_id, customer_name, balance, status)
VALUES
    ('ACC1001', 'CUST001', 'Ravi Kumar',     50000.00, 'ACTIVE'),
    ('ACC1002', 'CUST002', 'Priya Sharma',   30000.00, 'ACTIVE'),
    ('ACC1003', 'CUST003', 'Amit Patel',     75000.00, 'ACTIVE');

-- Verify:
SELECT account_number, customer_name, balance, status FROM accounts;
